### PR TITLE
fix posixpath, etc

### LINKED ISSUE #331: Not Load Zites...
### Step 1: Please describe your environment

  * ZeroNet version: [05:33:42] - zeronet-conservancy 0.7.10+ (source from main-81d3ffc6bdfb600e9a1d4a091f1ceb131d92c4f1-dirty) on Python 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] Gevent 25.9.1
  * Operating system: Debian 13
  * Web browser: Vivaldi
  * Tor status: not available
  * Opened port: yes
  * Special configuration: setuptools<82

### Step 2: Describe the problem:

Not Load Zites...

(venv) quasin@deskmini:~/Temp/ZeroNet$ python3 zeronet.py --no-dht
/home/quasin/Temp/ZeroNet

|||   . . _  _._|_     _. . . _ .__ _.. _.  . __.. _  __.  .
|||  //\|/ |/_| |  == /  / \|/ |(  /_||/ |  | __||/ |/   \_|
|||  \_/|  |\_  |.    \__\_/|  |_) \_ |   \/ |__||  |\__ _/
|||
|||  v0.7.10+

[05:33:42] - Libsecpk256k1 loaded: Lib in 0.001s
[05:33:42] - zeronet-conservancy 0.7.10+ (source from main-81d3ffc6bdfb600e9a1d4a091f1ceb131d92c4f1-dirty) on Python 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] Gevent 25.9.1
[05:33:42] FileServer IPv6 not supported: [Errno 101] Network is unreachable
[05:33:42] - Creating UiServer....
[05:33:42] SiteManager Loading sites... (cleanup=True, startup=True)
[05:33:42] SiteManager Added 12 sites in 0.003s
[05:33:42] Db#1:ContentDb Loaded 2 optional files: 0.03MB, downloaded: 0.00MB in 0.000s
[05:33:42] - Removing old SSL certs...
[05:33:42] - Starting servers....
[05:33:42] Site:13gLfT..RuXw ContentDb not initialized, load files from filesystem...
[05:33:42] Site:186THq..z84o ContentDb not initialized, load files from filesystem...
[05:33:42] Site:1EfLnw..ZTMq ContentDb not initialized, load files from filesystem...
[05:33:42] Site:1HELLo..Ri9d ContentDb not initialized, load files from filesystem...
[05:33:42] Site:1MaiL5..Ju27 ContentDb not initialized, load files from filesystem...
[05:33:42] Site:1MeFqF..q7nH ContentDb not initialized, load files from filesystem...
[05:33:42] Site:1SiTEs..tdwB ContentDb not initialized, load files from filesystem...
[05:33:42] Site:1TaLkF..jipT ContentDb not initialized, load files from filesystem...
[05:33:42] Site:1xiwbX..Fdo6 ContentDb not initialized, load files from filesystem...
[05:33:42] Ui.UiServer --------------------------------------
[05:33:42] Ui.UiServer Web interface: http://127.0.0.1:43110/
[05:33:42] Ui.UiServer --------------------------------------
[05:33:42] TorManager Tor controller connect error: ConnectionRefusedError: [Errno 111] Connection refused in TorManager.py line 143 > <gevent>/_socketcommon.py line 586 > 630
[05:33:42] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: Error ([Errno 111] Connection refused)
[05:33:43] Site:1MaiL5..Ju27 content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:43] WorkerManager:1MaiL5..Ju27 154.205.129.7:37874: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 1
[05:33:44] Site:1MaiL5..Ju27 content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:44] WorkerManager:1MaiL5..Ju27 116.202.216.125:26552: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 1, workers: 2
[05:33:44] Site:13gLfT..RuXw content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:44] WorkerManager:13gLfT..RuXw 111.237.115.101:15441: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 2
[05:33:44] Site:1EfLnw..ZTMq content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:44] WorkerManager:1EfLnw..ZTMq 111.237.115.101:15441: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 2
[05:33:45] Site:13gLfT..RuXw content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:45] WorkerManager:13gLfT..RuXw 158.220.126.220:42069: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 1, workers: 5
[05:33:46] Site:1EfLnw..ZTMq content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:46] WorkerManager:1EfLnw..ZTMq 51.79.160.138:15441: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 1, workers: 4
[05:33:49] Ui.UiServer Added 127.0.0.1:43110 as allowed host
[05:33:56] Site:1MeFqF..q7nH content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:56] WorkerManager:1MeFqF..q7nH 111.237.115.101:15441: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 1
[05:33:57] WorkerManager:13gLfT..RuXw 144.202.20.117:21447: Verify failed: content.json, error: No response, failed peers: 2, workers: 4
[05:33:57] WorkerManager:1EfLnw..ZTMq 217.18.217.143:31274: Verify failed: content.json, error: No response, failed peers: 2, workers: 3
[05:33:57] WorkerManager:1EfLnw..ZTMq 217.18.217.143:39288: Verify failed: content.json, error: No response, failed peers: 3, workers: 3
[05:33:57] WorkerManager:1EfLnw..ZTMq 79.127.131.194:20675: Verify failed: content.json, error: No response, failed peers: 4, workers: 3
[05:33:57] WorkerManager:13gLfT..RuXw 79.127.131.194:20675: Verify failed: content.json, error: No response, failed peers: 3, workers: 4
[05:33:57] WorkerManager:13gLfT..RuXw 0.0.0.4:1: Verify failed: content.json, error: No response, failed peers: 4, workers: 4
[05:33:57] Site:186THq..z84o content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:57] WorkerManager:186THq..z84o 158.220.126.220:42069: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 1
[05:33:57] Site:1SiTEs..tdwB content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:57] WorkerManager:1SiTEs..tdwB 154.205.129.7:37874: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 1
[05:33:57] Site:1MeFqF..q7nH content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:57] WorkerManager:1MeFqF..q7nH 213.177.213.113:22200: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 1, workers: 5
[05:33:58] WorkerManager:186THq..z84o 84.244.46.79:36488: Verify failed: content.json, error: No response, failed peers: 1, workers: 6
[05:33:58] Site:1TaLkF..jipT content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1TaLkF..jipT 116.202.216.125:26552: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 6
[05:33:58] WorkerManager:1SiTEs..tdwB 45.9.156.106:15441: Verify failed: content.json, error: No response, failed peers: 1, workers: 6
[05:33:58] Site:1TaLkF..jipT content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1TaLkF..jipT 154.205.129.7:37874: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 1, workers: 6
[05:33:58] Site:1HELLo..Ri9d content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1HELLo..Ri9d 37.195.194.70:15505: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 0, workers: 6
[05:33:58] Site:1HELLo..Ri9d content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1HELLo..Ri9d 37.195.194.70:11321: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 1, workers: 6
[05:33:58] Site:1SiTEs..tdwB content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1SiTEs..tdwB 213.177.213.113:22200: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 2, workers: 6
[05:33:58] Site:1TaLkF..jipT content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1TaLkF..jipT 213.177.213.113:22200: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 2, workers: 6
[05:33:58] Site:186THq..z84o content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:186THq..z84o 178.67.158.179:30693: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 2, workers: 5
[05:33:58] Site:186THq..z84o content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:186THq..z84o 111.237.115.101:15441: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 3, workers: 5
[05:33:58] Site:1TaLkF..jipT content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1TaLkF..jipT 111.237.115.101:15441: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 3, workers: 6
[05:33:58] Site:1HELLo..Ri9d content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:58] WorkerManager:1HELLo..Ri9d 109.248.148.247:43040: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 2, workers: 6
[05:33:59] Site:1HELLo..Ri9d content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:33:59] WorkerManager:1HELLo..Ri9d 77.26.132.123:20675: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 3, workers: 6
[05:34:00] Site:1SiTEs..tdwB content.json: verify sign error: VerifyError: Wrong inner_path: content.json in ContentManager.py line 1047 > 915
[05:34:00] WorkerManager:1SiTEs..tdwB 167.179.130.32:14613: Verify failed: content.json, error: Wrong inner_path: content.json, failed peers: 3, workers: 3
^C[05:34:00] - Shutting down (reason: Keyboard interrupt)...
[05:34:00] Site:191Caz..g2um WebSocket receive error: cancel_wait_ex: [Errno 9] File descriptor was closed in another greenlet in UiWebsocket.py line 75 > lib/gevent_ws/__init__.py line 80 > 86 > 48 > 105 > 125 > 156 > <gevent>/_socketcommon.py line 662 > <gevent>/_hub_primitives.py line 317 > 322 > 304 > 55 > <gevent>/_waiter.py line 154 > <gevent>/_greenlet_primitives.py line 65 > <gevent>/_gevent_c_greenlet_primitives.pxd line 35
[05:34:02] - All server stopped

### PR DESCRIPTION
**Pull request by milahu**
fix #331 

NOTE this disables validation of messages in c7c0a9ea8f67ec7932bb2aa76c44d215e154513f
otherwise all messages fail to validate
maybe there is a better fix

### CODE REVIEW

**Comment by slrslr** [comment]
@milahu are you able access site Like Millchan and Galactichan?
http://127.0.0.1:43110/19HKdTAeBh5nRiKn791czY7TwRB1QNrf1Q
http://127.0.0.1:43110/1ADQAHsqsie5PBeQhQgjcKmUu3qdPFg6aA/

In my case the error is:
```
dfe30ba
If this message doesn't go away try updating ZeroNet
```

this is not a issue of your PR/commits IMO. I think the issue is in plugins/FilePack/FilePackPlugin.py

old file which should be working (to open Millchan), but does not contain this PR fixes, is: https://paaster.io/69bbd753e98dd57c6d957c5c#Xa7P7_19XrQRZ46KJvSv6A9Px4hoAdF44frHQSDnkMU
current file resulting out of your PR(patch) where millchan does not work: https://paaster.io/69bbd718e98dd57c6d957c5a#0JYHod8O2m_IWhKI21SL-0arwuYZFIjRuqPvlZYFjHU

**Comment by milahu** [comment]
> Millchan and Galactichan

do these work for you with 805a3615ed777ff9d13877db15e69717813d3293 and c2c7e12efbe7b52856c60afe756bd6b4ae312339?

for me, they both fail with

```
Not Found
/media/19HKdTAeBh5nRiKn791czY7TwRB1QNrf1Q/
```

```
Not Found
/media/1ADQAHsqsie5PBeQhQgjcKmUu3qdPFg6aA/
```

i dont see errors on stdout, so i will have to add debug prints

**Comment by slrslr** [comment]
> do these work for you with [805a361](https://github.com/zeronet-conservancy/zeronet-conservancy/commit/805a3615ed777ff9d13877db15e69717813d3293) and [c2c7e12](https://github.com/zeronet-conservancy/zeronet-conservancy/commit/c2c7e12efbe7b52856c60afe756bd6b4ae312339)?

@milahu This is what I did in attempt to answer your questions:

stop ZNC
git status
`On branch pr-335`
git checkout 805a361
`HEAD is now at 805a3615 fix: AttributeError: 'str' object has no attribute 'parts'`
start ZNC
open Galactichan to see on-page the issue "If this message doesn't go away try updating ZeroNet" remains.

stop ZNC
git switch -
`Switched to branch 'pr-335'`
git checkout c2c7e12
`error: pathspec 'c2c7e12' did not match any file(s) known to git`
git fetch --all; git checkout c2c7e12
`error: pathspec 'c2c7e12' did not match any file(s) known to git`
git fetch origin c2c7e12
`fatal: couldn't find remote ref c2c7e12`
start ZNC
open Galactichan to see on-page the issue "If this message doesn't go away try updating ZeroNet" remains.
git switch -
`fatal: a branch is expected, got commit '805a3615ed777ff9d13877db15e69717813d3293'`
git checkout pr-335
```
Already on 'pr-335'
Your branch is ahead of 'origin/main' by 14 commits.
```
git pull
`Already up to date.`

**Comment by milahu** [comment]
> `error: pathspec 'c2c7e12' did not match any file(s) known to git`

805a361 and c2c7e12 are the last commits in this PR
so you just have to

```
# git fetch origin pull/335/head:pr-335 # create branch pr-335
git checkout pr-335
git pull
git rev-parse HEAD # should print c2c7e12...
```

at least that works with git version 2.53.0

**Comment by slrslr** [comment]
@milahu 

git fetch origin pull/335/head:pr-335 # create branch pr-335
`fatal: refusing to fetch into branch 'refs/heads/pr-335' checked out at '/home/zeronet/zeronetcpy312-pr335-branch'`

git checkout pr-335
```
Already on 'pr-335'
Your branch is ahead of 'origin/main' by 14 commits.
  (use "git push" to publish your local commits)
```

git pull
`Already up to date.`

git rev-parse HEAD # should print c2c7e12...
`da00605f96257708e417e143b93a6815bfa945d9`

git --version
`git version 2.43.0`

I have tried merging the earlier linked plugins/FilePack/FilePackPlugin.py files as a layman but ending up with ZNC-PR335 console error: `Error 500: Error while trying to serve site data` and on-site message remains "If this message doesn't go away try updating ZeroNet" when loading the chan site (for example [MC](http://127.0.0.1:43110/1ADQAHsqsie5PBeQhQgjcKmUu3qdPFg6aA/?)). Console error is visible when you drag down and drop a site corner button.

**Comment by milahu** [comment]
> ```
> $ git rev-parse HEAD
> da00605...
> ```

probably you dont get c2c7e12efbe7b52856c60afe756bd6b4ae312339 due to your `git merge` commands

you can try to fetch my #335 branch again ...

```
git fetch origin pull/335/head:pr-335-2
git checkout pr-335-2
git rev-parse HEAD # should print c2c7e12...
git pull # update
```

... but probably wont help

im giving up

**Comment by slrslr** [comment]
Result:

```
$ git status;git fetch origin pull/335/head:pr-335-2
On branch pr-335
...
no changes added to commit (use "git add" and/or "git commit -a")
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 8), reused 6 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 1.06 KiB | 83.00 KiB/s, done.
From https://github.com/zeronet-conservancy/zeronet-conservancy
 * [new ref]           refs/pull/335/head -> pr-335-2

$ git checkout pr-335-2
M       plugins/FilePack/FilePackPlugin.py
Switched to branch 'pr-335-2'

$ git rev-parse HEAD # should print c2c7e12...
c2c7e12efbe7b52856c60afe756bd6b4ae312339

$ git pull # update
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> pr-335-2
```

full, non shortened output is at https://paaster.io/69bfd307e98dd57c6d957ce1#YzoXwp46TSom_w3dPVlYjgUo67cZUy7D2QtwlkbA2V0

the error in a site console `Error 500: Error while trying to serve site data` remains as mentioned

> im giving up

I guess I will be unable to use that chan sites, but [you have made working publishing on Zeronet](https://github.com/zeronet-conservancy/zeronet-conservancy/issues/325#issuecomment-4089067025) in this PR, so thank you for that.
